print("Welcome to the story of the anime nerd.")
print("Once upon a time, a kid was born on the 12th of May.")
print("It turns out he was 12 when he was born and really enjoyed the outdoors.")
print("This boy was insurmountably imaginative.")
adjective1 = input("If there was one adjective that described the boy it was: ")
game = input("He was fascinated by the game: ")
adjective2 = input("He was also defined as: ")
friend = input("He always chilled under the umbrella with his friend: ")
verb = input(" Enter a verb that they did under the umbrella : ") 
adjective3 = input("His friend was: ")
print("That  was his normal summer day.")
